version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - ./meitukong:/code
    depends_on:
     - mysql

  mysql:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
    - "/vagrant/sql/Dump20160425.sql:/code/Dump20160425.sql"
    - "/vagrant/datadir:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD : 123456
